Traceback (most recent call last):
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
    """Train and Test"""
    model, y_pred = train_and_test(model_name, x_train, x_test, y_train, y_test)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_18392/3407684657.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;34m"""Train and Test"""[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mmodel[0m[1;33m,[0m [0my_pred[0m [1;33m=[0m [0mtrain_and_test[0m[1;33m([0m[0mmodel_name[0m[1;33m,[0m [0mx_train[0m[1;33m,[0m [0mx_test[0m[1;33m,[0m [0my_train[0m[1;33m,[0m [0my_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_18392/901221277.py[0m in [0;36mtrain_and_test[1;34m(model_name, x_train, x_test, y_train, y_test)[0m
[0;32m      7[0m     [0mmodel[0m [1;33m=[0m [0mCategoricalNB[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     [0mmodel[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mx_train[0m[1;33m,[0m [0my_train[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m     [0my_pred[0m [1;33m=[0m [0mmodel[0m[1;33m.[0m[0mpredict[0m[1;33m([0m[0mx_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     10[0m [1;33m[0m[0m
[0;32m     11[0m     [1;31m# Profile: End[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\mybook\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36mpredict[1;34m(self, X)[0m
[0;32m     73[0m         [0mcheck_is_fitted[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     74[0m         [0mX[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_check_X[0m[1;33m([0m[0mX[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 75[1;33m         [0mjll[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_joint_log_likelihood[0m[1;33m([0m[0mX[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     76[0m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mclasses_[0m[1;33m[[0m[0mnp[0m[1;33m.[0m[0margmax[0m[1;33m([0m[0mjll[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m     77[0m [1;33m[0m[0m

[1;32m~\.conda\envs\mybook\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36m_joint_log_likelihood[1;34m(self, X)[0m
[0;32m   1301[0m         [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mn_features_[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1302[0m             [0mindices[0m [1;33m=[0m [0mX[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m [0mi[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1303[1;33m             [0mjll[0m [1;33m+=[0m [0mself[0m[1;33m.[0m[0mfeature_log_prob_[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m[[0m[1;33m:[0m[1;33m,[0m [0mindices[0m[1;33m][0m[1;33m.[0m[0mT[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1304[0m         [0mtotal_ll[0m [1;33m=[0m [0mjll[0m [1;33m+[0m [0mself[0m[1;33m.[0m[0mclass_log_prior_[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1305[0m         [1;32mreturn[0m [0mtotal_ll[0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexError[0m: index 197 is out of bounds for axis 1 with size 99
IndexError: index 197 is out of bounds for axis 1 with size 99

