Traceback (most recent call last):
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\RyanJoung\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\RyanJoung\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Train and Test
cm, cr = train_and_test(model_name, x_train, x_test, y_train, y_test)
print('\n-----Confusion Matrix-----\n')
print(cm)
print('\n-----Classification Report-----\n')
print(cr)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_29316/2709227883.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Train and Test[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mcm[0m[1;33m,[0m [0mcr[0m [1;33m=[0m [0mtrain_and_test[0m[1;33m([0m[0mmodel_name[0m[1;33m,[0m [0mx_train[0m[1;33m,[0m [0mx_test[0m[1;33m,[0m [0my_train[0m[1;33m,[0m [0my_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mprint[0m[1;33m([0m[1;34m'\n-----Confusion Matrix-----\n'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mprint[0m[1;33m([0m[0mcm[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mprint[0m[1;33m([0m[1;34m'\n-----Classification Report-----\n'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_29316/2425710557.py[0m in [0;36mtrain_and_test[1;34m(model_name, x_train, x_test, y_train, y_test)[0m
[0;32m      7[0m     [0mmodel[0m [1;33m=[0m [0mCategoricalNB[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     [0mmodel[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mx_train[0m[1;33m,[0m [0my_train[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m     [0my_pred[0m [1;33m=[0m [0mmodel[0m[1;33m.[0m[0mpredict[0m[1;33m([0m[0mx_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     10[0m [1;33m[0m[0m
[0;32m     11[0m     [1;31m# Profile: End[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36mpredict[1;34m(self, X)[0m
[0;32m     81[0m         [0mcheck_is_fitted[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     82[0m         [0mX[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_check_X[0m[1;33m([0m[0mX[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 83[1;33m         [0mjll[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_joint_log_likelihood[0m[1;33m([0m[0mX[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     84[0m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mclasses_[0m[1;33m[[0m[0mnp[0m[1;33m.[0m[0margmax[0m[1;33m([0m[0mjll[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m     85[0m [1;33m[0m[0m

[1;32m~\OneDrive - Datapod Pty Ltd\Desktop\uc\mybook\my_book\venv\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36m_joint_log_likelihood[1;34m(self, X)[0m
[0;32m   1459[0m         [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mn_features_in_[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1460[0m             [0mindices[0m [1;33m=[0m [0mX[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m [0mi[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1461[1;33m             [0mjll[0m [1;33m+=[0m [0mself[0m[1;33m.[0m[0mfeature_log_prob_[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m[[0m[1;33m:[0m[1;33m,[0m [0mindices[0m[1;33m][0m[1;33m.[0m[0mT[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1462[0m         [0mtotal_ll[0m [1;33m=[0m [0mjll[0m [1;33m+[0m [0mself[0m[1;33m.[0m[0mclass_log_prior_[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1463[0m         [1;32mreturn[0m [0mtotal_ll[0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexError[0m: index 84 is out of bounds for axis 1 with size 31
IndexError: index 84 is out of bounds for axis 1 with size 31

